name: "🐞 Bug Report"
description: Report a Bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Before submitting, please note:

         - Confirm that your problem cannot be solved by official documentation.
         - Make sure you searched in the [Issues](https://github.com/zhixiaoqiang/sfc-playground-vant/issues) and didn't find the same issue.

  - type: textarea
    id: versions
    attributes:
      label: Version
      description: Use the `pnpm ls pnpm ls` command.
      placeholder: |
        dependencies:
        @vue/repl 1.0.0
        file-saver 2.0.5
        jszip 3.9.1
        vue 3.2.31
      render: sh
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the Bug, including screenshots, etc.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Reproduce link
      description: "Please provide a simplest reproduction of the problem (minimal demo without redundant dependencies). You can create it on CodePen ([<kbd>⌘</kbd>Click here to open the template](https://sfc-playground-vant.vercel.app/)), or provide the URL of the project:"
      placeholder: paste link here
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Reproduce Steps
      description: Please provide the simplest steps so that we can quickly reproduce the problem.
      placeholder: |
        for example:
        1. execute `pnpm dev`
        2. find `xxx` error message in the console
    validations:
      required: true