name: Deploy Playground

on:
  push:
    branches: [dev, main]

jobs:
  deploy-playground-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run:  pnpm install --no-frozen-lockfile

      - name: Build playground
        run: pnpm build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: vant-sfc-playground-gh-page
          folder: dist

      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     source-repo: git@github.com:zhixiaoqiang/sfc-playground-vant.git
      #     destination-repo: git@gitee.com:zhixiaoqiang/sfc-playground-vant.git